blue-team:
  item-shop-location:
    x: -7.559
    y: 42.5
    z: 4.619
    pitch: 0
    yaw: 0

pink-team:
  item-shop-location:
    x: -7.559
    y: 42.5
    z: 14.448
    pitch: 0
    yaw: 179.9

green-team:
  item-shop-location:
    x: -7.559
    y: 42.5
    z: 14.448
    pitch: 0
    yaw: 179.9
   
yellow-team:
  item-shop-location:
    x: -7.559
    y: 42.5
    z: 14.448
    pitch: 0
    yaw: 179.9
  
cyan-team:
  item-shop-location:
    x: -7.559
    y: 42.5
    z: 14.448
    pitch: 0
    yaw: 179.9  
      
red-team:
  item-shop-location:
    x: -7.559
    y: 42.5
    z: 14.448
    pitch: 0
    yaw: 179.9
    
white-team:
  item-shop-location:
    x: -7.559
    y: 42.5
    z: 14.448
    pitch: 0
    yaw: 179.9
    
gray-team:
  item-shop-location:
    x: -7.559
    y: 42.5
    z: 14.448
    pitch: 0
    yaw: 179.9