game:
  lobby:
    world-name: underwater_bedwars_lobby
    spawn-location:
      x: 0
      y: 100
      z: 0
  world-name: underwater_bedwars_map
  game-level:
    level-1:
      delay-ticks: 6000
      tier: Diamond II
    level-2:
      delay-ticks: 7200
      tier: Emerald II
    level-3:
      delay-ticks: 7200
      tier: Diamond III
    level-4:
      delay-ticks: 7200
      tier: Emerald III
    level-5:
      delay-ticks: 7200
      tier: Beds gone
    level-6:
      delay-ticks: 12000
      tier: Sudden death
    level-7:
      delay-ticks: 12000
      tier: Draw
  beds-gone-level: 1
  gens:
    gen_1:
      x: 1.5
      y: 44.5
      z: -46.5
      material: DIAMOND
      max-stack-size: 4
      level-0-delay-ticks: 600
      level-1-delay-ticks: 460
      level-2-delay-ticks: 460
      level-3-delay-ticks: 300
      level-4-delay-ticks: 300
      level-5-delay-ticks: 300
      level-6-delay-ticks: 300
      level-7-delay-ticks: 300
    gen_2:
      x: 80
      y: 57.5
      z: 32
      material: EMERALD
      delay-ticks: 1200
      max-stack-size: 4
      level-0-delay-ticks: 1200
      level-1-delay-ticks: 1200
      level-2-delay-ticks: 900
      level-3-delay-ticks: 900
      level-4-delay-ticks: 600
      level-5-delay-ticks: 600
      level-6-delay-ticks: 600
      level-7-delay-ticks: 600

teams:
  blue-team:
    color: BLUE
    active: true
    base-bounds:
      x-min: -14
      x-max: 14
      z-min: 2
      z-max: 16
    gen-location:
      x: -12.5
      y: 44
      z: 9.5 
    item-shop-location:
      x: -7.559
      y: 42.5
      z: 4.619
      pitch: 0
      yaw: 0
    team-shop-location:
      x: -7.559
      y: 42.5
      z: 14.448
      pitch: 0
      yaw: 179.9
    bed-location:
      x: 7.5
      y: 43.5
      z: 9.5
      facing: EAST
    spawn-location:
      x: -7.5
      y: 43
      z: 9.5
      pitch: 0
      yaw: -90
    chest-location:
      x: -3.5
      y: 43.0
      z: 6.5
      block-face: WEST
    ender-chest-location:
      x: -3.5
      y: 43.0
      z: 12.5
      block-face: WEST
    
  pink-team:
    color: PINK
    active: false
    item-shop-location:
      x: -7.559
      y: 42.5
      z: 14.448
      pitch: 0
      yaw: 179.9

  green-team:
    color: GREEN
    active: false
    item-shop-location:
      x: -7.559
      y: 42.5
      z: 14.448
      pitch: 0
      yaw: 179.9
   
  yellow-team:
    color: YELLOW
    active: false
    item-shop-location:
      x: -7.559
      y: 42.5
      z: 14.448
      pitch: 0
      yaw: 179.9
  
  cyan-team:
    color: AQUA
    active: false
    item-shop-location:
      x: -7.559
      y: 42.5
      z: 14.448
      pitch: 0
      yaw: 179.9  
      
  red-team:
    color: RED
    active: false
    item-shop-location:
      x: -7.559
      y: 42.5
      z: 14.448
      pitch: 0
      yaw: 179.9
    
  white-team:
    color: RED
    active: false
    item-shop-location:
      x: -7.559
      y: 42.5
      z: 14.448
      pitch: 0
      yaw: 179.9
    
  gray-team:
    color: GRAY
    active: false
    item-shop-location:
      x: -7.559
      y: 42.5
      z: 14.448
      pitch: 0
      yaw: 179.9