main: com.alexlabbane.underwaterbedwars.UnderwaterBedwars
api: spigot
name: UnderwaterBedwars
version: '1.0'
api-version: 1.16
author: Alex Labbane

commands:
  toggle:
    description: Toggle effects
  testshop:
    description: Test the shop, duh
  setitemshoplocation:
    description: Move a teams item shop villager to a designated location
  bwteam:
    description: Operations on teams